load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("//:go_toolchain.bzl", "go_toolchain", "toolchain_config")
load(":export_file.bzl", "export_file")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

export_file(
    name = "symlink.bat",
    src = "symlink.bat",
)

go_toolchain(
    name = "go",
    archive_extension = toolchain_config.archive_extension,
    platform = toolchain_config.platform,
    sha256 = toolchain_config.sha256,
    version = toolchain_config.version,
    visibility = ["PUBLIC"],
)
