load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("//:rust_toolchain.bzl", "rust_local_toolchain")

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

rust_local_toolchain(
    name = "rust",
    command = "rustc",
    visibility = ["PUBLIC"],
)
