name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples: ["example", "example-go"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          dagger-version: 0.12.3
      - name: Run Dagger Pipelines
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          dagger run --progress=plain deno run -A ../src/dagger/runner.ts
        working-directory: ${{ matrix.examples }}
